### PR TITLE
Change root namespace to Interop

### PR DESCRIPTION
**Pull request by shadowhand**
This package does not (at this time) represent an accepted PSR.

### CODE REVIEW

**Comment by harikt** [comment]
As @weierophinney already approved for http-factory why not merge this also?

**Comment by mnapoli** [comment]
:+1: I thought that that package was a strict representation of the PSR

**Comment by weierophinney** [comment]
I'm not part of either team as a sponsor or contributor, @harikt; I was
only expressing approval/agreement.

**Comment by shadowhand** [comment]
@http-interop/http-middleware-contributors one of us needs to sign off on this.

**Comment by shadowhand** [comment]
@mindplay-dk please sign off on this so that I can merge and tag a release.

**Comment by shadowhand** [comment]
@http-interop/http-middleware-contributors someone please approve this so that we can put it on packagist.

**Comment by mindplay-dk** [comment]
For the record, I don't agree with this change.

But I seem to be the minority, so: approved so we can move ahead.

**Comment by weierophinney** [comment]
@mindplay-dk Care to elaborate? I'm curious why you don't agree...

**Comment by mindplay-dk** [comment]
@weierophinney just that, it seems like we're assuming failure. I'd rather assume success, and not have to make a breaking change if the PSR is approved, by then changing the namespace back again. If the PSR is rejected, that _is_ a breaking change, and a namespace change would then be a natural change.

If this was no longer a PSR, the namespace should of course change. At the moment, it _is_ a PSR, albeit unstable, so the PSR namespace seems appropriate.

Anyhow, bigger fish to fry, hence approved in the name of progress :-)

**Pull request merged**
