### PR TITLE
Remove client middleware from scope

### PR DESCRIPTION
**Pull request by shadowhand**
As per the discussion [1] on the FIG mailing list, attempting to define
a specification that work for client side middleware is ill advised.

It will be far better to address client middleware in a separate
proposal after the async proposal has been completed.

[1]: https://groups.google.com/d/msg/php-fig/vBk0BRgDe2s/GTaT0yKNBgAJ

### CODE REVIEW

**Comment by shadowhand** [comment]
cc @http-interop/http-middleware-contributors

**Comment by weierophinney** [comment]
I've been nervous about this change for a while, as I've been working on http-interop compatibility with Stratigility/Expressive. This approach — removing only `MiddlewareInterface` — works perfectly for me, as I do not need to change any code currently!

:+1: from me!

**Review by weierophinney — APPROVED** [review]

**Comment by weierophinney** [comment]
@shadowhand Any chance of a new tag that contains this change?

**Comment by shadowhand** [comment]
@weierophinney I'd like to tag after #25 and #26 are reviewed.

**Comment by weierophinney** [comment]
@shadowhand Fair enough! I've added reviews to each now.

**Pull request merged**
