### PR TITLE
Rename Frame to Delegate

### PR DESCRIPTION
**Pull request by shadowhand**
Attempt to resolve confusion as to the purpose of the "next" caller.

### CODE REVIEW

**Comment by shadowhand** [comment]
@mnapoli @mindplay-dk is this enough to satisfy the immediate concern regarding the name of the "next middleware" dispatcher?

**Comment by mindplay-dk** [comment]
I still would go with full-on `MiddlewareDelegateInterface` to be explicit - I know it's longer, but should raise less questions ("delegate of what?") and it's not like we'll be typing that interface name all day? ;-)

**Comment by shadowhand** [comment]
@mindplay-dk not sure I agree the interface needs to be longer. The interface is clearly in the HTTP namespace and will only be used in a middleware.

**Comment by mindplay-dk** [comment]
> The interface is clearly in the HTTP namespace and will only be used in a middleware.

Okay, good point.

**Comment by mnapoli** [comment]
Should the same change be reflected in PSR-15 and its meta document?

**Comment by shadowhand** [comment]
@mnapoli yes it should.

**Comment by mnapoli** [comment]
From your answer I didn't know if you already worked on it or planned to work on it, so … https://github.com/php-fig/fig-standards/pull/808

**Comment by shadowhand** [comment]
@mnapoli was planning on submitting a PR in the next 48 hours. Glad someone else took initiative. 😄

**Pull request merged**
